Repository DurgNomis-drol/mytoyota, pull requests merged in 2022-12, with the labels that each got.

#205 Add User-agent string to base headers
  mytoyota/const.py
Labels: bug

#211 Include a pre-commit check to determine if the poetry.lock file is up to date
  .pre-commit-config.yaml
  README.md
Labels: enhancement

#208 Include more references that only the 'europe' region is supported
  README.md
Labels: documentation
