Repository DurgNomis-drol/mytoyota, pull requests merged in 2024-01, with the labels that each got.

#265 Add weekly & yearly summaries
  mytoyota/models/endpoints/trips.py
  mytoyota/models/vehicle.py
  mytoyota/utils/helpers.py
  simple_client_example.py
  tests/test_utils/test_helpers.py
Labels: :rocket: feature

#269 Fix: Use pydantic 1.10 due to homeassistant incompatibility with pydantic>2.0
  poetry.lock
  pyproject.toml
Labels: :bug: bug

#271 Use PosixPath for path handling and create parent folders if they not exist
  mytoyota/controller.py
Labels: :bug: bug

#272 Fix car door lock status
  mytoyota/models/lock_status.py
Labels: :bug: bug

#274 Use dynamic versioning
  .github/workflows/build.yml
  .github/workflows/python-publish.yml
  poetry.lock
  pyproject.toml
Labels: :wrench: enhancement

#276 Downgrade poetry-publish action to 1.16
  .github/workflows/python-publish.yml
Labels: :game_die: dependencies

#278 Fix: Make `fuel_level` and `fuel_range` optional
  mytoyota/models/endpoints/electric.py
Labels: :bug: bug

#285 Fix: Make `dcm` and `electricalPlatformCode` optional
  mytoyota/models/endpoints/vehicle_guid.py
Labels: :bug: bug

#283 Fix: Make `fugage` and `rage` optional
  mytoyota/models/endpoints/status.py
Labels: :bug: bug

#286 Fix: Make `unit` and `value` optional
  mytoyota/models/endpoints/common.py
Labels: :bug: bug

#282 Fix: Inconsistency in statistics summaries
  mytoyota/models/vehicle.py
Labels: :bug: bug

#289 Fix: Make `fuel_level` optional
  mytoyota/models/endpoints/telemetry.py
Labels: :bug: bug

#288 Fix wrong `fuel_consumed` conversion and add `average_fuel_consumed`
  mytoyota/models/summary.py
  simple_client_example.py
Labels: :bug: bug, :rocket: feature

#294 Fix: `scores` fields can be `None` in `TripsResponseModel`
  mytoyota/models/endpoints/trips.py
Labels: :bug: bug

#293 Fix: NoneType object has no attribute `unit` in `self._electric.fuel_range.unit`
  mytoyota/models/dashboard.py
Labels: :bug: bug

#296 Enhancement: Add logging on api endpoints
  mytoyota/api.py
  mytoyota/client.py
  mytoyota/controller.py
  mytoyota/models/vehicle.py
  mytoyota/statistics.py
  mytoyota/utils/conversions.py
  mytoyota/utils/logging/log_config.yaml
  mytoyota/utils/logging/log_filters.py
  mytoyota/utils/logging/log_utils.py
  mytoyota/utils/logging/logging_config.py
  simple_client_example.py
  tests/test_utils/test_logs.py
Labels: :wrench: enhancement

#300 Enahncement: Set default log level to `ERROR` and log to stdout
  mytoyota/utils/logging/log_config.yaml
  simple_client_example.py
Labels: :wrench: enhancement

#297 Enhancement: Added a `py.typed` file so that `mypy` will know to use our type annotations
  mytoyota/py.typed
  pyproject.toml
Labels: :wrench: enhancement

#312 Feature: Add initial `ServiceHistoryResponseModel`
  mytoyota/api.py
  mytoyota/const.py
  mytoyota/models/endpoints/service_history.py
  mytoyota/models/service_history.py
  mytoyota/models/vehicle.py
  simple_client_example.py
  tests/data/endpoints/v1_service_history.json
  tests/test_api.py
Labels: :rocket: feature

#315 Bug: Remove stream entry from log_config.yaml
  mytoyota/utils/logging/log_config.yaml
Labels: :bug: bug

#298 Add `HTTPXMock` testing and drop Python 3.8 support
  .github/workflows/build.yml
  .github/workflows/linting.yml
  .github/workflows/testing.yml
  mytoyota/controller.py
  mytoyota/utils/logging/log_utils.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/integration_tests/conftest.py
  tests/integration_tests/data/authenticate_invalid_password.json
  tests/integration_tests/data/authenticate_invalid_username.json
  tests/integration_tests/data/authenticate_refresh_token.json
  tests/integration_tests/data/authenticate_working.json
  tests/integration_tests/data/cached_token.json
  tests/integration_tests/data/get_static_data.json
  tests/integration_tests/test_authentication.py
  tests/unit_tests/conftest.py
  tests/unit_tests/data/v1_global_remote_electric_status.json
  tests/unit_tests/data/v1_global_remote_status.json
  tests/unit_tests/data/v1_location_error.json
  tests/unit_tests/data/v1_location_ok.json
  tests/unit_tests/data/v1_service_history.json
  tests/unit_tests/data/v1_trips.json
  tests/unit_tests/data/v1_vehicle_health_error.json
  tests/unit_tests/data/v1_vehicle_health_ok.json
  tests/unit_tests/data/v2_notification.json
  tests/unit_tests/data/v2_vehicleguid.json
  tests/unit_tests/data/v3_telemetry.json
  tests/unit_tests/data/v4_accountmodel.json
  tests/unit_tests/test_api.py
  tests/unit_tests/test_client.py
  tests/unit_tests/test_init.py
  tests/unit_tests/test_models/test_lock_status.py
  tests/unit_tests/test_utils/test_conversions.py
  tests/unit_tests/test_utils/test_formatter.py
  tests/unit_tests/test_utils/test_helpers.py
  tests/unit_tests/test_utils/test_locale.py
  tests/unit_tests/test_utils/test_logs.py
Labels: :warning: breaking change, :wrench: enhancement
